import type { CommerceCategory, CommerceProductDetail } from './business.types';

export const COMMERCE_CATEGORIES: CommerceCategory[] = [
  { id: 'bracelet', name: '手串', shortName: '手串', sortOrder: 10, isVisible: true },
  { id: 'crystal-ornament', name: '水晶摆件', shortName: '摆件', sortOrder: 20, isVisible: true },
  { id: 'crystal-pendant', name: '水晶吊坠', shortName: '吊坠', sortOrder: 30, isVisible: true },
  { id: 'crystal-earring', name: '水晶耳饰', shortName: '耳饰', sortOrder: 40, isVisible: true },
  { id: 'wood-ornament', name: '木制摆件', shortName: '木作', sortOrder: 50, isVisible: true },
];

export const COMMERCE_PRODUCTS: CommerceProductDetail[] = [
  {
    id: 'bracelet-clear-quartz-10mm',
    categoryId: 'bracelet',
    title: '白水晶圆珠手串 10mm',
    coverImageUrl: null,
    priceFen: 12800,
    badges: [
      { code: 'custom', label: '可定制' },
      { code: 'hot', label: '热销' },
    ],
    stockStatus: 'in_stock',
    isCustomizable: true,
    description: '通透白水晶单圈手串，适合作为日常佩戴与入门款。',
    gallery: [{ id: 'g1', imageUrl: null, alt: '白水晶圆珠手串主图' }],
    specs: ['8mm', '10mm', '12mm'],
    skus: [
      { id: 'sku-bq-8', label: '8mm · 默认手围', specValues: ['8mm'], priceFen: 11800, stock: 18 },
      { id: 'sku-bq-10', label: '10mm · 默认手围', specValues: ['10mm'], priceFen: 12800, stock: 12, isDefault: true },
      { id: 'sku-bq-12', label: '12mm · 默认手围', specValues: ['12mm'], priceFen: 14800, stock: 7 },
    ],
    serviceNotes: [
      { code: 'custom', label: '支持定制', detail: '支持调整手围、隔珠和礼盒卡片。' },
      { code: 'delivery', label: '发货说明', detail: '现货 48 小时内发出，定制款顺延。' },
      { code: 'after-sale', label: '售后说明', detail: '非定制质量问题支持 7 天内售后。' },
    ],
    detailSections: [
      { id: 'd1', title: '材质说明', content: '天然白水晶存在轻微冰裂与矿缺，属于正常现象。' },
      { id: 'd2', title: '佩戴建议', content: '避免与香水、洗护用品直接接触，久戴后可软布擦拭。' },
    ],
    favoriteCount: 23,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
  {
    id: 'bracelet-green-phantom',
    categoryId: 'bracelet',
    title: '绿幽灵单圈手串',
    coverImageUrl: null,
    priceFen: 26800,
    badges: [
      { code: 'new', label: '新品' },
      { code: 'custom', label: '可定制' },
    ],
    stockStatus: 'in_stock',
    isCustomizable: true,
    description: '绿幽灵圆珠配简洁隔珠，色泽沉稳。',
    gallery: [{ id: 'g2', imageUrl: null, alt: '绿幽灵单圈手串主图' }],
    specs: ['9mm', '10mm'],
    skus: [
      { id: 'sku-gp-9', label: '9mm · 默认手围', specValues: ['9mm'], priceFen: 25800, stock: 5 },
      { id: 'sku-gp-10', label: '10mm · 默认手围', specValues: ['10mm'], priceFen: 26800, stock: 4, isDefault: true },
    ],
    serviceNotes: [
      { code: 'custom', label: '支持定制', detail: '支持加隔珠、改绳材与礼盒包装。' },
      { code: 'care', label: '保养建议', detail: '避免高温暴晒，长期不用请单独收纳。' },
    ],
    detailSections: [{ id: 'd3', title: '风格说明', content: '适合作为偏成熟气质的日常搭配。' }],
    favoriteCount: 10,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
  {
    id: 'ornament-amethyst-tree',
    categoryId: 'crystal-ornament',
    title: '紫水晶发财树摆件',
    coverImageUrl: null,
    priceFen: 39900,
    badges: [{ code: 'gift', label: '送礼推荐' }],
    stockStatus: 'preorder',
    isCustomizable: false,
    description: '桌面紫晶树摆件，适合办公桌或玄关陈列。',
    gallery: [{ id: 'g3', imageUrl: null, alt: '紫水晶发财树摆件主图' }],
    specs: ['小号', '中号'],
    skus: [
      { id: 'sku-at-small', label: '小号', specValues: ['小号'], priceFen: 39900, stock: 3, isDefault: true },
      { id: 'sku-at-mid', label: '中号', specValues: ['中号'], priceFen: 52900, stock: 2 },
    ],
    serviceNotes: [{ code: 'preorder', label: '预售说明', detail: '摆件需加固包装，默认 3 到 5 天发货。' }],
    detailSections: [{ id: 'd4', title: '摆放建议', content: '适合 1.2m 以下桌面，不建议潮湿环境长期摆放。' }],
    favoriteCount: 8,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
  {
    id: 'pendant-rose-heart',
    categoryId: 'crystal-pendant',
    title: '粉晶爱心吊坠',
    coverImageUrl: null,
    priceFen: 8900,
    badges: [{ code: 'gift', label: '礼物款' }],
    stockStatus: 'in_stock',
    isCustomizable: false,
    description: '粉晶爱心小吊坠，适合叠戴或送礼。',
    gallery: [{ id: 'g5', imageUrl: null, alt: '粉晶爱心吊坠主图' }],
    specs: ['吊坠单件'],
    skus: [{ id: 'sku-rh-1', label: '吊坠单件', specValues: ['吊坠单件'], priceFen: 8900, stock: 16, isDefault: true }],
    serviceNotes: [{ code: 'gift', label: '包装说明', detail: '默认附送基础卡片与防尘袋。' }],
    detailSections: [{ id: 'd5', title: '佩戴建议', content: '建议搭配细链或编织绳使用。' }],
    favoriteCount: 5,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
  {
    id: 'earring-clear-drop',
    categoryId: 'crystal-earring',
    title: '白水晶水滴耳饰',
    coverImageUrl: null,
    priceFen: 15900,
    badges: [{ code: 'new', label: '新品' }],
    stockStatus: 'in_stock',
    isCustomizable: false,
    description: '轻量耳饰，适合日常佩戴。',
    gallery: [{ id: 'g6', imageUrl: null, alt: '白水晶水滴耳饰主图' }],
    specs: ['一对'],
    skus: [{ id: 'sku-ed-1', label: '一对', specValues: ['一对'], priceFen: 15900, stock: 10, isDefault: true }],
    serviceNotes: [{ code: 'care', label: '保养建议', detail: '耳钩为镀金件，建议干燥保存。' }],
    detailSections: [{ id: 'd6', title: '材质说明', content: '白水晶配金色耳钩，存在轻微手作差异。' }],
    favoriteCount: 9,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
  {
    id: 'wood-incense-seat',
    categoryId: 'wood-ornament',
    title: '胡桃木香插摆件',
    coverImageUrl: null,
    priceFen: 23900,
    badges: [{ code: 'craft', label: '手作' }],
    stockStatus: 'in_stock',
    isCustomizable: false,
    description: '胡桃木底座搭配黄铜香插，适合茶席场景。',
    gallery: [{ id: 'g7', imageUrl: null, alt: '胡桃木香插摆件主图' }],
    specs: ['标准款'],
    skus: [{ id: 'sku-wi-1', label: '标准款', specValues: ['标准款'], priceFen: 23900, stock: 6, isDefault: true }],
    serviceNotes: [{ code: 'care', label: '保养建议', detail: '木制品请远离水汽，定期薄涂木蜡油。' }],
    detailSections: [{ id: 'd7', title: '使用说明', content: '建议搭配短线香，使用时注意桌面耐热。' }],
    favoriteCount: 4,
    isFavorited: false,
    canAddToCart: true,
    canBuyNow: true,
  },
];
